// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import "package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart";
import "package:miria/rust/frb_generated.dart";

/// 組み込んでいる AiScript のバージョン。
Future<String> aiscriptVersion() =>
    RustLib.instance.api.crateApiAiscriptAiscriptVersion();

/// スクリプトを実行し、`<:` で出力された行を返す。
///
/// Rust 連携が通っているかを確かめるための最小実装。Play 本体の環境
/// (Mk:api / Ui:C:* など) はまだ生えていない。
Future<List<String>> eval({required String input}) =>
    RustLib.instance.api.crateApiAiscriptEval(input: input);
