// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_u8`

/// JPEG XL を読む。読めなければ `None`。
///
/// アニメーションのものは最初のキーフレームだけを返す。
Future<DecodedImage?> decodeJpegXl({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageCodecDecodeJpegXl(bytes: bytes);

/// JPEG XR を読む。読めなければ `None`。
///
/// jxrlib (Microsoft が公開した参照実装) に任せる。素の `Copy` は 8bit の
/// 形式で必ず失敗するので、フォーマットコンバータを噛ませたうえで、
/// その前にデコーダのアルファモードを立てておく。この2つが揃わないと
/// 8bit は読めない (imagecodecs の Python バインディングと同じ手順)。
Future<DecodedImage?> decodeJpegXr({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageCodecDecodeJpegXr(bytes: bytes);

/// デコード結果。`rgba` には RGBA8 が width * height * 4 バイト並ぶ。
class DecodedImage {
  final int width;
  final int height;
  final Uint8List rgba;

  const DecodedImage({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedImage &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}
