
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_dynamic_calls
    - cancel_subscriptions
    - close_sinks
    - discarded_futures
    - literal_only_boolean_expressions
    - no_self_assignments
    - prefer_void_to_null
    - unnecessary_statements
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_classes_with_only_static_members
    - avoid_private_typedef_functions
    # - avoid_redundant_argument_values
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - directives_ordering
    - eol_at_end_of_file
    - join_return_with_assignment
    - matching_super_parameters
    - no_literal_bool_comparisons
    - omit_local_variable_types
    - one_member_abstracts
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_double_quotes
    - prefer_final_in_for_each
    - prefer_final_locals
    - avoid_final_parameters
    - prefer_if_elements_to_conditional_expressions
    - prefer_null_aware_method_calls
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_breaks
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings

analyzer:
  exclude:
    - /**/*.freezed.dart
    - /**/*.g.dart
  plugins:
    - custom_lint
  language:
    # strict-casts: true
    # strict-inference: true
    # strict-raw-types: true