// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/aiscript.dart';
import 'api/aiscript/api.dart';
import 'api/aiscript/play.dart';
import 'api/aiscript/plugin.dart';
import 'api/aiscript/ui.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AiScriptPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsApiLibPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsPluginLibPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsUiButtonCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsUiLibPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsUiMfmCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsUiNumberCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsUiSelectCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsUiSwitchCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsUiTextInputCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AsUiTextareaCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PluginActionCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PluginInterruptorCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PluginPostFormActionCallbackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AiScript
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    dynamic raw,
  );

  @protected
  AsApiLib
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    dynamic raw,
  );

  @protected
  AsPluginLib
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    dynamic raw,
  );

  @protected
  AsUiButtonCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    dynamic raw,
  );

  @protected
  AsUiLib
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    dynamic raw,
  );

  @protected
  AsUiMfmCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    dynamic raw,
  );

  @protected
  AsUiNumberCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    dynamic raw,
  );

  @protected
  AsUiSelectCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    dynamic raw,
  );

  @protected
  AsUiSwitchCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    dynamic raw,
  );

  @protected
  AsUiTextInputCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    dynamic raw,
  );

  @protected
  AsUiTextareaCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    dynamic raw,
  );

  @protected
  PluginActionCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    dynamic raw,
  );

  @protected
  PluginInterruptorCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    dynamic raw,
  );

  @protected
  PluginPostFormActionCallback
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    dynamic raw,
  );

  @protected
  AiScript
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    dynamic raw,
  );

  @protected
  AsUiButtonCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    dynamic raw,
  );

  @protected
  AsUiMfmCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    dynamic raw,
  );

  @protected
  AsUiNumberCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    dynamic raw,
  );

  @protected
  AsUiSelectCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    dynamic raw,
  );

  @protected
  AsUiSwitchCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    dynamic raw,
  );

  @protected
  AsUiTextInputCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    dynamic raw,
  );

  @protected
  AsUiTextareaCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    dynamic raw,
  );

  @protected
  PluginActionCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    dynamic raw,
  );

  @protected
  PluginInterruptorCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    dynamic raw,
  );

  @protected
  PluginPostFormActionCallback
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(String, PluginInterruptorCallback)
  dco_decode_DartFn_Inputs_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(String, PluginPostFormActionCallback)
  dco_decode_DartFn_Inputs_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<String> Function(String)
  dco_decode_DartFn_Inputs_String_Output_String_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(String)
  dco_decode_DartFn_Inputs_String_Output_unit_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(String, String, PluginActionCallback)
  dco_decode_DartFn_Inputs_String_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(String, String)
  dco_decode_DartFn_Inputs_String_String_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<bool> Function(String, String, String)
  dco_decode_DartFn_Inputs_String_String_String_Output_bool_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(String, String, String)
  dco_decode_DartFn_Inputs_String_String_String_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<(String, String?)> Function(String, String, String?)
  dco_decode_DartFn_Inputs_String_String_opt_String_Output_record_string_opt_string_AnyhowException(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(String, AsUiComponent, PlatformInt64)
  dco_decode_DartFn_Inputs_String_as_ui_component_i_64_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  AiScript
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    dynamic raw,
  );

  @protected
  AsApiLib
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    dynamic raw,
  );

  @protected
  AsPluginLib
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    dynamic raw,
  );

  @protected
  AsUiButtonCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    dynamic raw,
  );

  @protected
  AsUiLib
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    dynamic raw,
  );

  @protected
  AsUiMfmCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    dynamic raw,
  );

  @protected
  AsUiNumberCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    dynamic raw,
  );

  @protected
  AsUiSelectCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    dynamic raw,
  );

  @protected
  AsUiSwitchCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    dynamic raw,
  );

  @protected
  AsUiTextInputCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    dynamic raw,
  );

  @protected
  AsUiTextareaCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    dynamic raw,
  );

  @protected
  PluginActionCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    dynamic raw,
  );

  @protected
  PluginInterruptorCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    dynamic raw,
  );

  @protected
  PluginPostFormActionCallback
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AsPlayLib dco_decode_as_play_lib(dynamic raw);

  @protected
  AsUiButton dco_decode_as_ui_button(dynamic raw);

  @protected
  AsUiButtons dco_decode_as_ui_buttons(dynamic raw);

  @protected
  AsUiComponent dco_decode_as_ui_component(dynamic raw);

  @protected
  AsUiContainer dco_decode_as_ui_container(dynamic raw);

  @protected
  AsUiFolder dco_decode_as_ui_folder(dynamic raw);

  @protected
  AsUiMfm dco_decode_as_ui_mfm(dynamic raw);

  @protected
  AsUiNumberInput dco_decode_as_ui_number_input(dynamic raw);

  @protected
  AsUiPostForm dco_decode_as_ui_post_form(dynamic raw);

  @protected
  AsUiPostFormButton dco_decode_as_ui_post_form_button(dynamic raw);

  @protected
  AsUiRoot dco_decode_as_ui_root(dynamic raw);

  @protected
  AsUiSelect dco_decode_as_ui_select(dynamic raw);

  @protected
  AsUiSwitch dco_decode_as_ui_switch(dynamic raw);

  @protected
  AsUiText dco_decode_as_ui_text(dynamic raw);

  @protected
  AsUiTextInput dco_decode_as_ui_text_input(dynamic raw);

  @protected
  AsUiTextarea dco_decode_as_ui_textarea(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AsApiLib
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    dynamic raw,
  );

  @protected
  AsPluginLib
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    dynamic raw,
  );

  @protected
  AsUiButtonCallback
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    dynamic raw,
  );

  @protected
  AsUiLib
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    dynamic raw,
  );

  @protected
  AsUiMfmCallback
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    dynamic raw,
  );

  @protected
  AsUiNumberCallback
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    dynamic raw,
  );

  @protected
  AsUiSelectCallback
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    dynamic raw,
  );

  @protected
  AsUiSwitchCallback
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    dynamic raw,
  );

  @protected
  AsUiTextInputCallback
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    dynamic raw,
  );

  @protected
  AsUiTextareaCallback
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    dynamic raw,
  );

  @protected
  AsPlayLib dco_decode_box_autoadd_as_play_lib(dynamic raw);

  @protected
  AsUiButton dco_decode_box_autoadd_as_ui_button(dynamic raw);

  @protected
  AsUiButtons dco_decode_box_autoadd_as_ui_buttons(dynamic raw);

  @protected
  AsUiContainer dco_decode_box_autoadd_as_ui_container(dynamic raw);

  @protected
  AsUiFolder dco_decode_box_autoadd_as_ui_folder(dynamic raw);

  @protected
  AsUiMfm dco_decode_box_autoadd_as_ui_mfm(dynamic raw);

  @protected
  AsUiNumberInput dco_decode_box_autoadd_as_ui_number_input(dynamic raw);

  @protected
  AsUiPostForm dco_decode_box_autoadd_as_ui_post_form(dynamic raw);

  @protected
  AsUiPostFormButton dco_decode_box_autoadd_as_ui_post_form_button(dynamic raw);

  @protected
  AsUiRoot dco_decode_box_autoadd_as_ui_root(dynamic raw);

  @protected
  AsUiSelect dco_decode_box_autoadd_as_ui_select(dynamic raw);

  @protected
  AsUiSwitch dco_decode_box_autoadd_as_ui_switch(dynamic raw);

  @protected
  AsUiText dco_decode_box_autoadd_as_ui_text(dynamic raw);

  @protected
  AsUiTextInput dco_decode_box_autoadd_as_ui_text_input(dynamic raw);

  @protected
  AsUiTextarea dco_decode_box_autoadd_as_ui_textarea(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PostFormPropsForAsUi dco_decode_box_autoadd_post_form_props_for_as_ui(
    dynamic raw,
  );

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AsUiButton> dco_decode_list_as_ui_button(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AsApiLib?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    dynamic raw,
  );

  @protected
  AsPluginLib?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    dynamic raw,
  );

  @protected
  AsUiButtonCallback?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    dynamic raw,
  );

  @protected
  AsUiLib?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    dynamic raw,
  );

  @protected
  AsUiMfmCallback?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    dynamic raw,
  );

  @protected
  AsUiNumberCallback?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    dynamic raw,
  );

  @protected
  AsUiSelectCallback?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    dynamic raw,
  );

  @protected
  AsUiSwitchCallback?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    dynamic raw,
  );

  @protected
  AsUiTextInputCallback?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    dynamic raw,
  );

  @protected
  AsUiTextareaCallback?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    dynamic raw,
  );

  @protected
  AsPlayLib? dco_decode_opt_box_autoadd_as_play_lib(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PostFormPropsForAsUi? dco_decode_opt_box_autoadd_post_form_props_for_as_ui(
    dynamic raw,
  );

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<AsUiButton>? dco_decode_opt_list_as_ui_button(dynamic raw);

  @protected
  List<(String, String)>? dco_decode_opt_list_record_string_string(dynamic raw);

  @protected
  PostFormPropsForAsUi dco_decode_post_form_props_for_as_ui(dynamic raw);

  @protected
  (String, String?) dco_decode_record_string_opt_string(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AiScript
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    SseDeserializer deserializer,
  );

  @protected
  AsApiLib
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    SseDeserializer deserializer,
  );

  @protected
  AsPluginLib
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    SseDeserializer deserializer,
  );

  @protected
  AsUiButtonCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiLib
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    SseDeserializer deserializer,
  );

  @protected
  AsUiMfmCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiNumberCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSelectCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSwitchCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextInputCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextareaCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    SseDeserializer deserializer,
  );

  @protected
  PluginActionCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    SseDeserializer deserializer,
  );

  @protected
  PluginInterruptorCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    SseDeserializer deserializer,
  );

  @protected
  PluginPostFormActionCallback
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    SseDeserializer deserializer,
  );

  @protected
  AiScript
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    SseDeserializer deserializer,
  );

  @protected
  AsUiButtonCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiMfmCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiNumberCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSelectCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSwitchCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextInputCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextareaCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    SseDeserializer deserializer,
  );

  @protected
  PluginActionCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    SseDeserializer deserializer,
  );

  @protected
  PluginInterruptorCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    SseDeserializer deserializer,
  );

  @protected
  PluginPostFormActionCallback
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    SseDeserializer deserializer,
  );

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  AiScript
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    SseDeserializer deserializer,
  );

  @protected
  AsApiLib
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    SseDeserializer deserializer,
  );

  @protected
  AsPluginLib
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    SseDeserializer deserializer,
  );

  @protected
  AsUiButtonCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiLib
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    SseDeserializer deserializer,
  );

  @protected
  AsUiMfmCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiNumberCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSelectCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSwitchCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextInputCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextareaCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    SseDeserializer deserializer,
  );

  @protected
  PluginActionCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    SseDeserializer deserializer,
  );

  @protected
  PluginInterruptorCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    SseDeserializer deserializer,
  );

  @protected
  PluginPostFormActionCallback
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AsPlayLib sse_decode_as_play_lib(SseDeserializer deserializer);

  @protected
  AsUiButton sse_decode_as_ui_button(SseDeserializer deserializer);

  @protected
  AsUiButtons sse_decode_as_ui_buttons(SseDeserializer deserializer);

  @protected
  AsUiComponent sse_decode_as_ui_component(SseDeserializer deserializer);

  @protected
  AsUiContainer sse_decode_as_ui_container(SseDeserializer deserializer);

  @protected
  AsUiFolder sse_decode_as_ui_folder(SseDeserializer deserializer);

  @protected
  AsUiMfm sse_decode_as_ui_mfm(SseDeserializer deserializer);

  @protected
  AsUiNumberInput sse_decode_as_ui_number_input(SseDeserializer deserializer);

  @protected
  AsUiPostForm sse_decode_as_ui_post_form(SseDeserializer deserializer);

  @protected
  AsUiPostFormButton sse_decode_as_ui_post_form_button(
    SseDeserializer deserializer,
  );

  @protected
  AsUiRoot sse_decode_as_ui_root(SseDeserializer deserializer);

  @protected
  AsUiSelect sse_decode_as_ui_select(SseDeserializer deserializer);

  @protected
  AsUiSwitch sse_decode_as_ui_switch(SseDeserializer deserializer);

  @protected
  AsUiText sse_decode_as_ui_text(SseDeserializer deserializer);

  @protected
  AsUiTextInput sse_decode_as_ui_text_input(SseDeserializer deserializer);

  @protected
  AsUiTextarea sse_decode_as_ui_textarea(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AsApiLib
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    SseDeserializer deserializer,
  );

  @protected
  AsPluginLib
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    SseDeserializer deserializer,
  );

  @protected
  AsUiButtonCallback
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiLib
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    SseDeserializer deserializer,
  );

  @protected
  AsUiMfmCallback
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiNumberCallback
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSelectCallback
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSwitchCallback
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextInputCallback
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextareaCallback
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsPlayLib sse_decode_box_autoadd_as_play_lib(SseDeserializer deserializer);

  @protected
  AsUiButton sse_decode_box_autoadd_as_ui_button(SseDeserializer deserializer);

  @protected
  AsUiButtons sse_decode_box_autoadd_as_ui_buttons(
    SseDeserializer deserializer,
  );

  @protected
  AsUiContainer sse_decode_box_autoadd_as_ui_container(
    SseDeserializer deserializer,
  );

  @protected
  AsUiFolder sse_decode_box_autoadd_as_ui_folder(SseDeserializer deserializer);

  @protected
  AsUiMfm sse_decode_box_autoadd_as_ui_mfm(SseDeserializer deserializer);

  @protected
  AsUiNumberInput sse_decode_box_autoadd_as_ui_number_input(
    SseDeserializer deserializer,
  );

  @protected
  AsUiPostForm sse_decode_box_autoadd_as_ui_post_form(
    SseDeserializer deserializer,
  );

  @protected
  AsUiPostFormButton sse_decode_box_autoadd_as_ui_post_form_button(
    SseDeserializer deserializer,
  );

  @protected
  AsUiRoot sse_decode_box_autoadd_as_ui_root(SseDeserializer deserializer);

  @protected
  AsUiSelect sse_decode_box_autoadd_as_ui_select(SseDeserializer deserializer);

  @protected
  AsUiSwitch sse_decode_box_autoadd_as_ui_switch(SseDeserializer deserializer);

  @protected
  AsUiText sse_decode_box_autoadd_as_ui_text(SseDeserializer deserializer);

  @protected
  AsUiTextInput sse_decode_box_autoadd_as_ui_text_input(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextarea sse_decode_box_autoadd_as_ui_textarea(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PostFormPropsForAsUi sse_decode_box_autoadd_post_form_props_for_as_ui(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AsUiButton> sse_decode_list_as_ui_button(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AsApiLib?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    SseDeserializer deserializer,
  );

  @protected
  AsPluginLib?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    SseDeserializer deserializer,
  );

  @protected
  AsUiButtonCallback?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiLib?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    SseDeserializer deserializer,
  );

  @protected
  AsUiMfmCallback?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiNumberCallback?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSelectCallback?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiSwitchCallback?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextInputCallback?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsUiTextareaCallback?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    SseDeserializer deserializer,
  );

  @protected
  AsPlayLib? sse_decode_opt_box_autoadd_as_play_lib(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PostFormPropsForAsUi? sse_decode_opt_box_autoadd_post_form_props_for_as_ui(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<AsUiButton>? sse_decode_opt_list_as_ui_button(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)>? sse_decode_opt_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  PostFormPropsForAsUi sse_decode_post_form_props_for_as_ui(
    SseDeserializer deserializer,
  );

  @protected
  (String, String?) sse_decode_record_string_opt_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    AiScript self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    AsApiLib self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    AsPluginLib self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    AsUiButtonCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    AsUiLib self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    AsUiMfmCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    AsUiNumberCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    AsUiSelectCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    AsUiSwitchCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    AsUiTextInputCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    AsUiTextareaCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    PluginActionCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    PluginInterruptorCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    PluginPostFormActionCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    AiScript self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    AsUiButtonCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    AsUiMfmCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    AsUiNumberCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    AsUiSelectCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    AsUiSwitchCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    AsUiTextInputCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    AsUiTextareaCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    PluginActionCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    PluginInterruptorCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    PluginPostFormActionCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback_Output_unit_AnyhowException(
    FutureOr<void> Function(String, PluginInterruptorCallback) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback_Output_unit_AnyhowException(
    FutureOr<void> Function(String, PluginPostFormActionCallback) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_Output_String_AnyhowException(
    FutureOr<String> Function(String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback_Output_unit_AnyhowException(
    FutureOr<void> Function(String, String, PluginActionCallback) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String, String) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_String_String_Output_bool_AnyhowException(
    FutureOr<bool> Function(String, String, String) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_String_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String, String, String) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_String_opt_String_Output_record_string_opt_string_AnyhowException(
    FutureOr<(String, String?)> Function(String, String, String?) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_String_as_ui_component_i_64_Output_unit_AnyhowException(
    FutureOr<void> Function(String, AsUiComponent, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    AiScript self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    AsApiLib self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    AsPluginLib self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    AsUiButtonCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    AsUiLib self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    AsUiMfmCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    AsUiNumberCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    AsUiSelectCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    AsUiSwitchCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    AsUiTextInputCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    AsUiTextareaCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    PluginActionCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    PluginInterruptorCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    PluginPostFormActionCallback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_as_play_lib(AsPlayLib self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_button(AsUiButton self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_buttons(AsUiButtons self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_component(AsUiComponent self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_container(AsUiContainer self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_folder(AsUiFolder self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_mfm(AsUiMfm self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_number_input(
    AsUiNumberInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_as_ui_post_form(AsUiPostForm self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_post_form_button(
    AsUiPostFormButton self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_as_ui_root(AsUiRoot self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_select(AsUiSelect self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_switch(AsUiSwitch self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_text(AsUiText self, SseSerializer serializer);

  @protected
  void sse_encode_as_ui_text_input(
    AsUiTextInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_as_ui_textarea(AsUiTextarea self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    AsApiLib self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    AsPluginLib self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    AsUiButtonCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    AsUiLib self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    AsUiMfmCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    AsUiNumberCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    AsUiSelectCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    AsUiSwitchCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    AsUiTextInputCallback self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    AsUiTextareaCallback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_play_lib(
    AsPlayLib self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_button(
    AsUiButton self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_buttons(
    AsUiButtons self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_container(
    AsUiContainer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_folder(
    AsUiFolder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_mfm(AsUiMfm self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_as_ui_number_input(
    AsUiNumberInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_post_form(
    AsUiPostForm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_post_form_button(
    AsUiPostFormButton self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_root(
    AsUiRoot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_select(
    AsUiSelect self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_switch(
    AsUiSwitch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_text(
    AsUiText self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_text_input(
    AsUiTextInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_as_ui_textarea(
    AsUiTextarea self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_post_form_props_for_as_ui(
    PostFormPropsForAsUi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_as_ui_button(
    List<AsUiButton> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    AsApiLib? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    AsPluginLib? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    AsUiButtonCallback? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    AsUiLib? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    AsUiMfmCallback? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    AsUiNumberCallback? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    AsUiSelectCallback? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    AsUiSwitchCallback? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    AsUiTextInputCallback? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    AsUiTextareaCallback? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_as_play_lib(
    AsPlayLib? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_post_form_props_for_as_ui(
    PostFormPropsForAsUi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_as_ui_button(
    List<AsUiButton>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_record_string_string(
    List<(String, String)>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_post_form_props_for_as_ui(
    PostFormPropsForAsUi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_opt_string(
    (String, String?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAiScript(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsApiLib(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsPluginLib(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiButtonCallback(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiLib(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiMfmCallback(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiNumberCallback(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSelectCallback(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiSwitchCallback(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextInputCallback(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAsUiTextareaCallback(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginActionCallback(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginInterruptorCallback(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPluginPostFormActionCallback(
    int ptr,
  );
}
