const misskeyIOReactionDelay = 1500;

class Font {
  final String displayName;
  final String actualName;

  const Font(this.displayName, this.actualName);
}

const choosableFonts = [
  Font("システム標準", ""),
  Font("Noto Sans Japanese", "Noto Sans JP"),
  // Font("Noto Serif Japanese", "Noto Serif Japanese"),
  Font("IBM Plex Sans JP", "IBM Plex Sans JP"),
  Font("ZEN角ゴシック", "Zen Kaku Gothic New"),
  Font("ZEN丸ゴシック", "Zen Maru Gothic"),
  Font("ZEN角ゴシックアンチック", "Zen Kaku Gothic Antique"),
  Font("Zenアンチック", "Zen Antique"),
  Font("ZENアンチックSoft", "Zen Antique Soft"),
  Font("ZENオールド明朝", "Zen Old Mincho"),
  Font("BIZ UD ゴシック", "BIZ UDGothic"),
  Font("BIZ UD Pゴシック", "BIZ UDPGothic"),
  Font("BIZ UD 明朝", "BIZ UDMincho"),
  Font("BIZ UD P明朝", "BIZ UDPMincho"),
  Font("M+ 1", "M PLUS 1"),
  Font("M+ 1P", "M PLUS 1p"),
  Font("M+ 1C", "M PLUS 1 Code"),
  Font("M+ 2", "M PLUS 2"),
  Font("M+ Rounded 1C", "M PLUS Rounded 1c"),
  Font("しっぽり明朝", "Shippori Mincho"),
  Font("しっぽり明朝B1", "Shippori Mincho B1"),
  Font("しっぽりアンチック", "Shippori Antique"),
  Font("しっぽりアンチックB1", "Shippori Antique B1"),
  Font("ひな明朝", "Hina Mincho"),
  Font("Kosugi", "Kosugi"),
  Font("Kosugi Maru", "Kosugi Maru"),
  Font("Kiwi Maru", "Kiwi Maru"),
  Font("牟礼町", "Murecho"),
  Font("さわらびゴシック", "Sawarabi Gothic"),
  Font("さわらび明朝", "Sawarabi Mincho"),
  Font("クレー One", "Klee One"),
  Font("ロックンロール One", "RocknRoll One"),
  Font("レゲエ One", "Reggae One"),
  Font("ランパート One", "Rampart One"),
  Font("ステッキ", "Stick"),
  Font("トレイン", "Train One"),
  Font("ドットゴシック16", "DotGothic16"),
  Font("デラゴシック", "Dela Gothic One"),
  Font("解星 デコール", "Kaisei Decol"),
  Font("解星 オプティ", "Kaisei Opti"),
  Font("解星 特ミン", "Kaisei Tokumin"),
  Font("解星 春の海", "Kaisei HarunoUmi"),
  Font("はちまるポップ", "Hachi Maru Pop"),
  Font("モッチーポップ", "Mochiy Pop P One"),
  Font("ZEN紅道", "Zen Kurenaido"),
  Font("佑字 舞", "Yuji Mai"),
  Font("佑字 肅", "Yuji Syuku"),
  Font("佑字 朴", "Yuji Boku"),
  Font("Yusei Magic", "Yusei Magic"),
  Font("よもぎフォント", "Yomogi"),
  Font("Potta One", "Potta One"),
  Font("ニューテゴミン", "New Tegomin"),
];
