// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `register_v0`, `register_v1`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< AsApiLib>>
abstract class AsApiLib implements RustOpaqueInterface {
  factory AsApiLib({
    String? userId,
    String? userName,
    String? userUsername,
    required String customEmojis,
    required String locale,
    required String serverUrl,
    required FutureOr<void> Function(String, String, String) dialog,
    required FutureOr<bool> Function(String, String, String) confirm,
    required FutureOr<void> Function(String) toast,
    String? token,
    required FutureOr<(String, String?)> Function(String, String, String?) api,
    required FutureOr<void> Function(String, String) save,
    required FutureOr<String> Function(String) load,
    required FutureOr<void> Function(String) remove,
    required String url,
    required FutureOr<String> Function(String) nyaize,
  }) => RustLib.instance.api.crateApiAiscriptApiAsApiLibNew(
    userId: userId,
    userName: userName,
    userUsername: userUsername,
    customEmojis: customEmojis,
    locale: locale,
    serverUrl: serverUrl,
    dialog: dialog,
    confirm: confirm,
    toast: toast,
    token: token,
    api: api,
    save: save,
    load: load,
    remove: remove,
    url: url,
    nyaize: nyaize,
  );
}
