// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `register_v0`, `register_v1`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// スクリプト冒頭のメタデータブロックを読む。
///
/// 本家の `parsePluginMeta` に対応する。名前なしのメタデータ (`### { ... }`)
/// を JSON にして返す。プラグインの名前やバージョンはここに入っている。
Future<String> parsePluginMeta({required String input}) =>
    RustLib.instance.api.crateApiAiscriptPluginParsePluginMeta(input: input);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< AsPluginLib>>
abstract class AsPluginLib implements RustOpaqueInterface {
  factory AsPluginLib({
    required String config,
    required FutureOr<void> Function(String) openUrl,
    required FutureOr<void> Function(String, String, PluginActionCallback)
    onAction,
    required FutureOr<void> Function(String, PluginPostFormActionCallback)
    onPostFormAction,
    required FutureOr<void> Function(String, PluginInterruptorCallback)
    onInterruptor,
  }) => RustLib.instance.api.crateApiAiscriptPluginAsPluginLibNew(
    config: config,
    openUrl: openUrl,
    onAction: onAction,
    onPostFormAction: onPostFormAction,
    onInterruptor: onInterruptor,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginActionCallback>>
abstract class PluginActionCallback implements RustOpaqueInterface {
  Future<void> call({required String value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginInterruptorCallback>>
abstract class PluginInterruptorCallback implements RustOpaqueInterface {
  Future<String> call({required String value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginPostFormActionCallback>>
abstract class PluginPostFormActionCallback implements RustOpaqueInterface {
  Future<String> call({required String form});
}
