name: miria # 'snapcraft register miria'で名前を予約する必要あり
title: Miria
type: app
summary: Misskey Client App # 79文字まで
description: |
  Miria is Misskey Client App for iOS, Android and many targets which made by Flutter.
  Miria includes these features.
  - Login, Logout, Management multiple servers and accounts
  - Show home, local, hybrid(social), global timelines, list, antenna and channel
  - Show note with MFM (Completely Supported).
  - Note, Renote, Quoted renote, renote to any channel
  - Reaction
  - Show Notifications
  - Edit antenna and list
  - Explore
  - Announcements
  - Favorite
  - Search notes and users
  - Page (show only)
  - Show Server Information (online users, job queue, ads, custom emojis)
license: AGPL-3.0
website: https://shiosyakeyakini.info/miria_web
source-code: https://github.com/shiosyakeyakini-info/miria
issues: https://github.com/shiosyakeyakini-info/miria/issues
donation: https://shiosyakeyakini.fanbox.cc
contact: sorairo@shiosyakeyakini.info
icon: assets/images/icon.png
adopt-info: miria
base: core22
grade: stable
confinement: strict
compression: lzo # 起動速度の向上（xz比）

apps:
  miria:
    command: miria
    extensions: [gnome]
    plugs:
      - home
      - unity7
      - network
      - audio-playback
      # 以下はユーザーが接続を許可するまで使用不可
      - removable-media # カメラのSDカードから直接取り込むユーザー向け
      - password-manager-service # ログイン情報の保存＆読み込みのため必須
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack

parts:
  miria:
    source: .
    #plugin: flutter
    plugin: nil
    build-environment:
      - PATH: "$CRAFT_PART_BUILD/FlutterSDK/bin:$PATH"
    build-packages:
      - libmpv-dev
      - libsecret-1-dev
      # flutterプラグインで使用されるパッケージ
      - clang
      - curl
      - git
      - cmake
      - ninja-build
      - unzip
      - jq
    stage-packages:
      - libmpv1
      - libsecret-1-0
    override-pull: |
      craftctl default
      craftctl set version=$(cat pubspec.yaml | grep "version[:]" | cut -d " " -f 2)
    override-build: |
      # flutterプラグインの処理を代替
      set +e
      rm -rf $CRAFT_PART_BUILD/FlutterSDK
      git clone --depth 1 -b $(jq -r .flutter .fvmrc) https://github.com/flutter/flutter.git $CRAFT_PART_BUILD/FlutterSDK
      flutter precache --linux
      flutter pub get
      set -e
      #flutter pub run build_runner build --delete-conflicting-outputs
      flutter build linux --release --verbose --target lib/main.dart
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/

  zenity:
  # Integrate custom dialogs in your snap - doc - snapcraft.io
  # https://forum.snapcraft.io/t/integrate-custom-dialogs-in-your-snap/10825
    plugin: nil
    stage-packages:
      - zenity
    prime:
      - usr/bin/zenity
      - usr/share/zenity/*
      - usr/share/doc/*/copyright*

  cleanup:
    after: [miria, zenity]  # Make this part run last; list all your other parts here
    plugin: nil
    build-snaps: [gnome-42-2204, gtk-common-themes, core22]  # List all content-snaps you're using here
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gtk-common-themes" "core22"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done

layout:
  # Fix resource relocation problem of zenity part
  /usr/share/zenity:
    symlink: $SNAP/usr/share/zenity

lint:
  ignore:
    - library:
      - lib/libmedia_kit_native_event_loop.so
