
name: デプロイ(linux)
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-snap:
    name: ビルド（Snap）
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.os }}
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Snap
        id: snapcraft
        uses: canonical/action-build@v1

      - name: Get Build Version
        run: |
          echo "VERSION=$(yq -r '.version' pubspec.yaml)" >> $GITHUB_ENV
      - name: Upload snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v$VERSION ${{ steps.snapcraft.outputs.snap }}
      # https://gihyo.jp/admin/serial/01/ubuntu-recipe/0660#sec3 : Snapパッケージアップロードまでの流れ
      # https://github.com/snapcore/action-publish : Snap ActionのREADME.md
      # Snap Storeでパッケージ名"miria"を予約（$ snapcraft register miria）後、"SNAPCRAFT_STORE_CREDENTIALS"を登録し、
      # 以下をコメントアウトを解除することでSnap Storeへアップロードすることが可能です。
      # 通常、SnapファイルをそのままStore外で公開することはありません。
      #
      #- name: Upload Snap Store
      #  uses: snapcore/action-publish@v1
      #  env:
      #    SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      #  with:
      #    snap: ${{ steps.snapcraft.outputs.snap }}
      #    release: stable

  build-deb:
    name: ビルド（deb）
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.os }}
    steps:
        - name: Clone repository
          uses: actions/checkout@v4

        - name: Set up Docker
          uses: docker/setup-buildx-action@v3

        - name: Set Environment Variables
          run: |
            NAME=$(yq -r '.name' pubspec.yaml)
            VERSION=$(yq -r '.version' pubspec.yaml)

            case "${{ runner.arch }}" in
              "X64" ) arch="amd64" ;;
              "ARM64" ) arch="arm64" ;;
            esac

            echo "PKG_DIR=${NAME}_${VERSION}_${arch}" >> $GITHUB_ENV
            echo "ARCH=$arch" >> $GITHUB_ENV
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Start Debian Build Container
          run: |
            docker run -dit --name debian \
              -v "${PWD}:/workspace" \
              -w /workspace \
              -e PKG_DIR="$PKG_DIR" \
              -e ARCH="$ARCH" \
              -e VERSION="$VERSION" \
              debian:bookworm \
              bash

        - name: Install Build Dependencies
          run: |
            docker exec debian bash -c '
                apt update
                apt install -y curl git unzip ninja-build libgtk-3-dev libsecret-1-dev libstdc++-12-dev nasm cmake libmpv-dev clang
                rm -rf /var/lib/apt/lists/*
            '

        - name: Install FVM
          run: |
            docker exec debian bash -c 'curl -fsSL https://fvm.app/install.sh | bash'

        - name: Set up flutter
          run: |
            docker exec debian bash -c 'fvm install --setup'
        
        - name: Build
          run: |
            docker exec debian bash -c '
                fvm flutter pub get
                fvm flutter build linux --release
            '

        - name: Prepare Package
          run: |
            docker exec debian bash -c '
                rm -rf "${PKG_DIR}"
                mkdir -p \
                    "${PKG_DIR}/opt/miria" \
                    "${PKG_DIR}/usr/bin"
                
                case "${ARCH}" in
                  "amd64" ) cp -rp ./build/linux/x64/release/bundle/* "${PKG_DIR}/opt/miria/" ;;
                  "arm64" ) cp -rp ./build/linux/arm64/release/bundle/* "${PKG_DIR}/opt/miria/" ;;
                esac

                install -Dm 644 ./snap/gui/miria.desktop "${PKG_DIR}/usr/share/applications/miria.desktop"
                install -Dm 644 ./assets/images/icon.png "${PKG_DIR}/usr/share/pixmaps/miria.png"
                install -Dm 644 ./LICENSE "${PKG_DIR}/usr/share/licenses/miria/LICENSE"
                ln -s /opt/miria/miria "${PKG_DIR}/usr/bin/miria"
                sed -i -E "s|^Version=.*|Version=1.5|g" "${PKG_DIR}/usr/share/applications/miria.desktop"
                sed -i -E "s|^Icon=.*|Icon=miria|g" "${PKG_DIR}/usr/share/applications/miria.desktop"

                install -Dm 644 ./linux/debian/control "${PKG_DIR}/DEBIAN/control"
                sed -i -E "s|^Version: .*|Version: ${VERSION}|g" "${PKG_DIR}/DEBIAN/control"
                sed -i -E "s|^Architecture: .*|Architecture: ${ARCH}|g" "${PKG_DIR}/DEBIAN/control"
            '
        
        - name: Generate .deb File
          run: |
            docker exec debian bash -c '
                dpkg-deb --build "${PKG_DIR}"
            '

        - name: Upload .deb File
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh release upload v$VERSION ./$PKG_DIR.deb